#!/bin/bash
file_name="hello"
group_name="school"
if [ -f "$file_name" ]; then
    chgrp "$group_name" "$file_name"
    echo "Group owner of '$file_name' changed to '$group_name'."
else
    echo "File '$file_name' not found in the working directory."
fi
