#!/bin/bash
file_name="hello"
if [ -f "$file_name" ]; then
    chmod u+x "$file_name"
    echo "Execute permission added to the owner of the file '$file_name'."
else
    echo "File '$file_name' not found in the working directory."
fi
