#!/bin/bash
# Check if the parent directory exists
parent_dir="../"
if [ ! -d "$parent_dir" ]; then
  echo "Parent directory not found."
  exit 1
fi
# Copy HTML files from the current directory to the parent directory
cp -u *.html "$parent_dir"
